# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: ls && dotnet build ./inOffice/inOfficeApplication --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Init EF Core'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-ef'

- task: DownloadSecureFile@1
  name: deploymentAppSettings
  displayName: 'Download appsettings for Azure'
  inputs:
    secureFile: 'appsettings.Production.json'
- task: CmdLine@2
  displayName: 'Move prod app settings'
  inputs:
    script: |
      ls
      mv $(deploymentAppSettings.secureFilePath) ./inOffice/inOfficeApplication
      cd ./inOffice/inOfficeApplication && ls
      cd ../inOfficeApplication.Data && dotnet ef database update

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Service Connection - inOffice'
    appType: 'webAppLinux'
    WebAppName: 'inofficeapinet'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|6.0'