trigger:
  - feature/*
  - bug/*
  - story/*
  - main

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build MyDesk Application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: ubuntu-latest
    
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: './MyDesk/MyDesk.Application/MyDesk.Application.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: './MyDesk/MyDesk.Application/MyDesk.Application.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: './MyDesk/MyDesk.UnitTests/MyDesk.UnitTests.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      inputs:
        command: 'publish'
        projects: './MyDesk/MyDesk.Application/MyDesk.Application.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      artifact: drop

- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to the dev environment'
    pool:
      vmImage: ubuntu-latest
    environment: 'development'
    variables:
    - group: mydesk-be-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'ITL Gold'
              appType: 'webAppLinux'
              WebAppName: $(AppServiceName)
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
              AppSettings: |
                -AllowedHosts "$(AllowedHosts)" 
                -ConnectionString "$(ConnectionString)" 
                -SentimentEndpoint "$(SentimentEndpoint)" 
                -TenantClaimKey "$(TenantClaimKey)" 
                -Tenants "$(Tenants)" 
                -AdminEmail "$(AdminEmail)" 
                -AdminPassword "$(AdminPassword)" 
                -Authentication__Local__CustomBearerTokenSigningKey "$(Authentication:Local:CustomBearerTokenSigningKey)" 
                -Authentication__AzureAd__Issuer "$(Authentication:AzureAd:Issuer)" 
                -Authentication__AzureAd__Audience "$(Authentication:AzureAd:Audience)" 
                -Authentication__AzureAd__MetadataAddress "$(Authentication:AzureAd:MetadataAddress)" 
                -Authentication__Google__Issuer "$(Authentication:Google:Issuer)" 
                -Authentication__Google__ClientId "$(Authentication:Google:ClientId)"

- stage: 'Production'
  displayName: 'Deploy to the prod environment'
  dependsOn: Dev
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to the prod environment'
    pool:
      vmImage: ubuntu-latest
    environment: 'production'
    variables:
    - group: mydesk-be-production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'ITL Gold'
              appType: 'webAppLinux'
              WebAppName: $(AppServiceName)
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
              AppSettings: |
                -AllowedHosts "$(AllowedHosts)" 
                -ConnectionString "$(ConnectionString)" 
                -SentimentEndpoint "$(SentimentEndpoint)" 
                -TenantClaimKey "$(TenantClaimKey)" 
                -Tenants "$(Tenants)" 
                -AdminEmail "$(AdminEmail)" 
                -AdminPassword "$(AdminPassword)" 
                -Authentication__Local__CustomBearerTokenSigningKey "$(Authentication:Local:CustomBearerTokenSigningKey)" 
                -Authentication__AzureAd__Issuer "$(Authentication:AzureAd:Issuer)" 
                -Authentication__AzureAd__Audience "$(Authentication:AzureAd:Audience)" 
                -Authentication__AzureAd__MetadataAddress "$(Authentication:AzureAd:MetadataAddress)" 
                -Authentication__Google__Issuer "$(Authentication:Google:Issuer)" 
                -Authentication__Google__ClientId "$(Authentication:Google:ClientId)"