// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using inOfficeApplication.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace inOfficeApplication.Data.Entities.Configurations
{
    public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.ToTable("Employee");

            entity.Property(e => e.Email).IsRequired();

            entity.Property(e => e.FirstName).IsRequired();

            entity.Property(e => e.IsAdmin)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(1)))");

            entity.Property(e => e.IsDeleted)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");

            entity.Property(e => e.LastName).IsRequired();

            entity.Property(e => e.Password).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
}
